name: Build Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "github-actions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: âš™ï¸ Set Gradle permissions
        run: chmod +x ./gradlew

      - name: ðŸ§ª Run build and tests
        run: ./gradlew build test

#      - name: ðŸŽ¯ Run Jacoco coverage check
#        run: ./gradlew jacocoTestReport jacocoTestCoverageVerification

      - name: ðŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set IMAGE_TAG as current date
        run: echo "IMAGE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: swaggermock
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
